<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <EmbeddedResource Include="_testFiles/*" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\src\bctklib\bctklib.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="6.0.4">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="FluentAssertions" Version="7.2.0" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
        <PackageReference Include="Neo.Plugins.Storage.RocksDBStore" Version="3.10.1" />
        <PackageReference Include="System.IO.Abstractions.TestingHelpers" Version="22.2.0" />
        <PackageReference Include="Xunit.Combinatorial" Version="2.1.41" />
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="xunit.v3" Version="3.1.0" />
    </ItemGroup>
</Project>
