variables:
  BuildConfiguration: Release

pool:
  vmImage: 'windows-2019'

trigger:
  batch: false
  branches:
    include:
    - master
    - insiders
    - release/*
  paths:
    include:
    - '*'
    exclude:
    - 'readme.md'
    - 'changelog.md'
    - 'docs/*'

steps:
- task: UseDotNet@2
  displayName: 'use .NET Core SDK from global.json'
  inputs:
    packageType: 'sdk'
    useGlobalJson: true

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack neo express 2'
  inputs:
    command: 'pack'
    packagesToPack: './src/neo-express/neo-express.csproj'
    includesymbols: true
    versioningScheme: 'off'

    
- task: DotNetCoreCLI@2
  displayName: 'dotnet pack neo express 3'
  inputs:
    command: 'pack'
    packagesToPack: './src/nxp3/nxp3.csproj'
    includesymbols: true
    versioningScheme: 'off'

- publish: '$(Build.ArtifactStagingDirectory)'
  displayName: 'publish build artifact'
  name: nugetPackage

- task: NuGetCommand@2
  displayName: 'NuGet push to NeoDevPackages feed'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '4b2bd186-f7a1-4f00-a22c-521ae5c47cd7/fc59ee4d-b5ed-4a8d-9520-240cd3712671'