name: On Pull Request (*.cs/ *.csproj Files)

on:
  pull_request:
    branches:
      - master
      - development
      - release/*
    paths:
      - '**.cs'
      - '**.csproj'

# Cancel old test actions when new commits are pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/test.yml
