name: On Pull Request

on:
  pull_request:
    branches:
      - master
      - development
      - release/*
    paths:
      - '**.cs'
      - '**.csproj'

jobs:
  test:
    uses: ./.github/workflows/test.yml
  pack:
    uses: ./.github/workflows/pack.yml
