name: On Pull Request

on:
  push:
    branches:
      - master
      - release/*
    paths-ignore:
      - '.gitignore'
      - '.gitattributes'
      - 'LICENSE'
      - '**/*.md'
  pull_request:
    branches:
      - master
      - release/*
    paths-ignore:
      - '.gitignore'
      - '.gitattributes'
      - 'LICENSE'
      - '**/*.md'

jobs:
  test:
    uses: ./.github/workflows/test.yml
  pack:
    needs: [test]
    uses: ./.github/workflows/pack.yml
  neoxp:
    needs: [pack, test]  
    uses: ./.github/workflows/neoxp.yml
