name: Run Publish (MyGet.org)

on:
  workflow_call:
    outputs:
      PrereleaseVersion:
        value: ${{ jobs.pack.outputs.PrereleaseVersion}}
      NuGetPackageVersion:
        value: ${{ jobs.pack.outputs.NuGetPackageVersion}}

env:
  CONFIGURATION: 'Release'
  DOTNET_VERSION: '7.0.x'

jobs:
  publish:
    runs-on: ubuntu-latest
    outputs:
      PrereleaseVersion: ${{ steps.nbgv.outputs.PrereleaseVersion }}
      NuGetPackageVersion: ${{ steps.nbgv.outputs.NuGetPackageVersion }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Nerdbank.GitVersioning
      uses: dotnet/nbgv@v0.4.1
      id: nbgv
        
    - name: Update submodule
      run: |
        git submodule update --init --recursive --remote 

    - name: Restore
      run: dotnet restore neo-express.sln

    - name: Build
      run: dotnet build neo-express.sln --configuration ${{ env.CONFIGURATION }} --no-restore --verbosity normal --BinaryLogger:./msbuild.binlog

    - name: Pack
      run: dotnet pack neo-express.sln --configuration ${{ env.CONFIGURATION }} --output ./out --no-build --verbosity normal

    - name: Publish Package to MyGet (Neo.Assertions)
      run: dotnet nuget push ./out/Neo.Assertions.*.nupkg --api-key ${{ secrets.MYGET_TOKEN }} --source https://www.myget.org/F/neo/api/v3/index.json

    - name: Publish Package to MyGet (Neo.BlockchainToolkit)
      run: dotnet nuget push ./out/Neo.BlockchainToolkit.*.nupkg --api-key ${{ secrets.MYGET_TOKEN }} --source https://www.myget.org/F/neo/api/v3/index.json

    - name: Publish Package to MyGet (Neo.BuildTasks)
      run: dotnet nuget push ./out/Neo.BuildTasks.*.nupkg --api-key ${{ secrets.MYGET_TOKEN }} --source https://www.myget.org/F/neo/api/v3/index.json

    - name: Publish Package to MyGet (Neo.Collector)
      run: dotnet nuget push ./out/Neo.Collector.*.nupkg --api-key ${{ secrets.MYGET_TOKEN }} --source https://www.myget.org/F/neo/api/v3/index.json

    - name: Publish Package to MyGet (Neo.Express)
      run: dotnet nuget push ./out/Neo.Express.*.nupkg --api-key ${{ secrets.MYGET_TOKEN }} --source https://www.myget.org/F/neo/api/v3/index.json

    - name: Publish Package to MyGet (Neo.Test.Harness)
      run: dotnet nuget push ./out/Neo.Test.Harness.*.nupkg --api-key ${{ secrets.MYGET_TOKEN }} --source https://www.myget.org/F/neo/api/v3/index.json

    - name: Publish Package to MyGet (Neo.Test.Runner)
      run: dotnet nuget push ./out/Neo.Test.Runner.*.nupkg --api-key ${{ secrets.MYGET_TOKEN }} --source https://www.myget.org/F/neo/api/v3/index.json

    # - name: Upload Build Log
    #   if: always() && (github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/development'))
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: buildlog
    #     path: ./msbuild.binlog
